config/routes.rb
Rails.application.routes.draw do

  resources :notes
  resources :questions
  resources :keywords
  resources :keywords
  resources :models
  resources :notebooks
  get 'dashboard/main'

  resources :notebooks

  root to: 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  has_many :keywords
  has_many :notes
  has_many :questions

  belongs_to :user

  validates :subject, presence: true
  validates :user_id, presence: true

end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
    @keywords = Keyword.all
    @questions = Question.all
    @notes = Note.all
    @keyword = Keyword.new
    @question = Question.new
    @note = Note.new
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.js { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.js
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notebook_params
      params.require(:notebook).permit(:subject, :user_id)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_for(@notebook) do |f| %>
  <% if @notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% @notebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/_keyword.html.erb
<%= form_for(@keyword, remote: true) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>
      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/_note.html.erb
<%= form_for(@note, remote: true) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>Note</h4><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.hidden_field :notebook_id, :value => @notebook.id  %>
  </div>
  <div class="actions noteSubmit">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/_notes.html.erb
<tr>
  <td><%= note.note %></td></p>
  <p class="showEditDestroy"><td><%= link_to 'Show', note %></td>
  <td><%= link_to 'Edit', edit_note_path(note) %></td>
  <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/notebooks/create.html.erb
<h1>Notebooks#create</h1>
<p>Find me in app/views/notebooks/create.html.erb</p>

app/views/notebooks/destroy.html.erb
<h1>Notebooks#destroy</h1>
<p>Find me in app/views/notebooks/destroy.html.erb</p>

app/views/notebooks/edit.html.erb
<h1>Editing Notebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notebooks</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= notebook.subject %></td>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>Notebooks#new</h1>
<p>Find me in app/views/notebooks/new.html.erb</p>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="subject">  <%= @notebook.subject %> </h2>



<div class="leftSide">
  <%= link_to "New Note", new_note_path, remote: true%>
<div class="notesDiv">
  <% @notes.each do |note| %>
    <div class="noteDetails"> <%= render partial: "notes", locals: {note: note} %> </div>
  <% end %>
 </div>
  <div class="notesForm"> </div>

</div>


<div class="rightSide">
  <div class="keywordForm">
    <%= form_for(@keyword, remote: true) do |f| %>
      <% if @keyword.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>
          <ul>
          <% @keyword.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :word %><br>
        <%= f.text_field :word %>
      </div>
      <div class="field">
        <%= f.label :definition %><br>
        <%= f.text_area :definition %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  <!-- <% @keywords.each do |keyword| %>
    <tr>
      <td><%= keyword.word %></td>
      <td><%= keyword.definition %></td>
      <td><%= link_to 'Show', keyword %></td>
      <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
      <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %> -->
  <%= link_to 'New Keyword', new_keyword_path %>

  <div class="keywordDiv"></div>

  <div class="questionForm">
    <%= form_for(@question, remote: true) do |f| %>
      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :question %><br>
        <%= f.text_field :question %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= link_to 'Show', question %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
      <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <%= link_to 'New Question', new_question_path %>

</div>


<div id="linkBack">
  <%= link_to 'Edit This Notebook', edit_notebook_path(@notebook) %> |
  <%= link_to 'Back to Index', notebooks_path %>
</div>